version: '3'
services:
  app:
    build:
      context: .
    ports:
      - "7000:7000"
    environment:
      - PATH=/root/miniconda3/bin:${PATH}
      - PATH=/opt/miniconda3/bin:${PATH}
    command: python app.py